### ISSUE TITLE
Добавьте больше элементов и формул

### ISSUE THREAD

**Issue by OkulusDev** [OkulusDev/Oxygen#2]
На момент [данного коммита](https://github.com/OkulusDev/Oxygen/commit/31c3c87ce49f9ef890eaf4328ad29b68afeaf03f) в Oxygen доступно только 11 элементов (с водорода до натрия включительно) и 1 формула (H2O, вода).

Вот пример ошибки, если я ввожу формулу ArFe(Ru)2:

```bash
Traceback (most recent call last):
  File "/home/okulus/Coding/Oxygen/oxygen/chemistry/base.py", line 46, in calculate_relative_molecular_mass
    print(f'{i[1]} {ELEMENTS[i[0]].name} = {ELEMENTS[i[0]].relative_atomic_mass * i[1]}')
                    ~~~~~~~~^^^^^^
KeyError: 'Ar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/okulus/Coding/Oxygen/oxygen.py", line 27, in <module>
    main()
  File "/home/okulus/Coding/Oxygen/oxygen.py", line 17, in main
    mass = calculate_relative_molecular_mass(formula, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/okulus/Coding/Oxygen/oxygen/chemistry/base.py", line 48, in calculate_relative_molecular_mass
    raise NameError(f'Element {i[0]} does not exists. Try other!')
NameError: Element Ar does not exists. Try other!
```

Нужна вся таблица менделеева, а также побольше бы формул

**Comment by OkulusDev** [comment]
Работа уже идет

**Comment by OkulusDev** [comment]
Мы добавили чтение из CSV файла с данными по каждому элементу (до 118 включительно). Добавил формулу сахарозу, скоро добавим больше формул

**Comment by OkulusDev** [comment]
Все готово!
